// Precalculated Bible reading plan for 2026 (365 days)
// Auto-generated by generate_2026_plan.py
// Parallel OT and NT reading plans
// OT: 929 chapters, NT: 260 chapters

typedef struct {
    const char *testament;  // "OT" or "NT"
    const char *book;
    int chapter;
} DailyReading;

typedef struct {
    int day_of_year;  // 1-365
    int count;        // Number of chapters total (OT + NT)
    DailyReading readings[10];  // Max 10 chapters per day
} DayPlan;

static const DayPlan daily_plan_2026[365] = {
    {1, 2, {{"OT", "Genesis", 1}, {"OT", "Genesis", 2}}}, // Day 1: OT: Genesis 1, Genesis 2 | NT: 
    {2, 4, {{"OT", "Genesis", 3}, {"OT", "Genesis", 4}, {"OT", "Genesis", 5}, {"NT", "Matthew", 1}}}, // Day 2: OT: Genesis 3, Genesis 4, Genesis 5 | NT: Matthew 1
    {3, 3, {{"OT", "Genesis", 6}, {"OT", "Genesis", 7}, {"NT", "Matthew", 2}}}, // Day 3: OT: Genesis 6, Genesis 7 | NT: Matthew 2
    {4, 3, {{"OT", "Genesis", 8}, {"OT", "Genesis", 9}, {"OT", "Genesis", 10}}}, // Day 4: OT: Genesis 8, Genesis 9, Genesis 10 | NT: 
    {5, 3, {{"OT", "Genesis", 11}, {"OT", "Genesis", 12}, {"NT", "Matthew", 3}}}, // Day 5: OT: Genesis 11, Genesis 12 | NT: Matthew 3
    {6, 4, {{"OT", "Genesis", 13}, {"OT", "Genesis", 14}, {"OT", "Genesis", 15}, {"NT", "Matthew", 4}}}, // Day 6: OT: Genesis 13, Genesis 14, Genesis 15 | NT: Matthew 4
    {7, 2, {{"OT", "Genesis", 16}, {"OT", "Genesis", 17}}}, // Day 7: OT: Genesis 16, Genesis 17 | NT: 
    {8, 4, {{"OT", "Genesis", 18}, {"OT", "Genesis", 19}, {"OT", "Genesis", 20}, {"NT", "Matthew", 5}}}, // Day 8: OT: Genesis 18, Genesis 19, Genesis 20 | NT: Matthew 5
    {9, 3, {{"OT", "Genesis", 21}, {"OT", "Genesis", 22}, {"NT", "Matthew", 6}}}, // Day 9: OT: Genesis 21, Genesis 22 | NT: Matthew 6
    {10, 4, {{"OT", "Genesis", 23}, {"OT", "Genesis", 24}, {"OT", "Genesis", 25}, {"NT", "Matthew", 7}}}, // Day 10: OT: Genesis 23, Genesis 24, Genesis 25 | NT: Matthew 7
    {11, 2, {{"OT", "Genesis", 26}, {"OT", "Genesis", 27}}}, // Day 11: OT: Genesis 26, Genesis 27 | NT: 
    {12, 4, {{"OT", "Genesis", 28}, {"OT", "Genesis", 29}, {"OT", "Genesis", 30}, {"NT", "Matthew", 8}}}, // Day 12: OT: Genesis 28, Genesis 29, Genesis 30 | NT: Matthew 8
    {13, 4, {{"OT", "Genesis", 31}, {"OT", "Genesis", 32}, {"OT", "Genesis", 33}, {"NT", "Matthew", 9}}}, // Day 13: OT: Genesis 31, Genesis 32, Genesis 33 | NT: Matthew 9
    {14, 2, {{"OT", "Genesis", 34}, {"OT", "Genesis", 35}}}, // Day 14: OT: Genesis 34, Genesis 35 | NT: 
    {15, 4, {{"OT", "Genesis", 36}, {"OT", "Genesis", 37}, {"OT", "Genesis", 38}, {"NT", "Matthew", 10}}}, // Day 15: OT: Genesis 36, Genesis 37, Genesis 38 | NT: Matthew 10
    {16, 3, {{"OT", "Genesis", 39}, {"OT", "Genesis", 40}, {"NT", "Matthew", 11}}}, // Day 16: OT: Genesis 39, Genesis 40 | NT: Matthew 11
    {17, 4, {{"OT", "Genesis", 41}, {"OT", "Genesis", 42}, {"OT", "Genesis", 43}, {"NT", "Matthew", 12}}}, // Day 17: OT: Genesis 41, Genesis 42, Genesis 43 | NT: Matthew 12
    {18, 2, {{"OT", "Genesis", 44}, {"OT", "Genesis", 45}}}, // Day 18: OT: Genesis 44, Genesis 45 | NT: 
    {19, 4, {{"OT", "Genesis", 46}, {"OT", "Genesis", 47}, {"OT", "Genesis", 48}, {"NT", "Matthew", 13}}}, // Day 19: OT: Genesis 46, Genesis 47, Genesis 48 | NT: Matthew 13
    {20, 3, {{"OT", "Genesis", 49}, {"OT", "Genesis", 50}, {"NT", "Matthew", 14}}}, // Day 20: OT: Genesis 49, Genesis 50 | NT: Matthew 14
    {21, 3, {{"OT", "Exodus", 1}, {"OT", "Exodus", 2}, {"OT", "Exodus", 3}}}, // Day 21: OT: Exodus 1, Exodus 2, Exodus 3 | NT: 
    {22, 3, {{"OT", "Exodus", 4}, {"OT", "Exodus", 5}, {"NT", "Matthew", 15}}}, // Day 22: OT: Exodus 4, Exodus 5 | NT: Matthew 15
    {23, 4, {{"OT", "Exodus", 6}, {"OT", "Exodus", 7}, {"OT", "Exodus", 8}, {"NT", "Matthew", 16}}}, // Day 23: OT: Exodus 6, Exodus 7, Exodus 8 | NT: Matthew 16
    {24, 4, {{"OT", "Exodus", 9}, {"OT", "Exodus", 10}, {"OT", "Exodus", 11}, {"NT", "Matthew", 17}}}, // Day 24: OT: Exodus 9, Exodus 10, Exodus 11 | NT: Matthew 17
    {25, 2, {{"OT", "Exodus", 12}, {"OT", "Exodus", 13}}}, // Day 25: OT: Exodus 12, Exodus 13 | NT: 
    {26, 4, {{"OT", "Exodus", 14}, {"OT", "Exodus", 15}, {"OT", "Exodus", 16}, {"NT", "Matthew", 18}}}, // Day 26: OT: Exodus 14, Exodus 15, Exodus 16 | NT: Matthew 18
    {27, 3, {{"OT", "Exodus", 17}, {"OT", "Exodus", 18}, {"NT", "Matthew", 19}}}, // Day 27: OT: Exodus 17, Exodus 18 | NT: Matthew 19
    {28, 3, {{"OT", "Exodus", 19}, {"OT", "Exodus", 20}, {"OT", "Exodus", 21}}}, // Day 28: OT: Exodus 19, Exodus 20, Exodus 21 | NT: 
    {29, 3, {{"OT", "Exodus", 22}, {"OT", "Exodus", 23}, {"NT", "Matthew", 20}}}, // Day 29: OT: Exodus 22, Exodus 23 | NT: Matthew 20
    {30, 4, {{"OT", "Exodus", 24}, {"OT", "Exodus", 25}, {"OT", "Exodus", 26}, {"NT", "Matthew", 21}}}, // Day 30: OT: Exodus 24, Exodus 25, Exodus 26 | NT: Matthew 21
    {31, 3, {{"OT", "Exodus", 27}, {"OT", "Exodus", 28}, {"NT", "Matthew", 22}}}, // Day 31: OT: Exodus 27, Exodus 28 | NT: Matthew 22
    {32, 3, {{"OT", "Exodus", 29}, {"OT", "Exodus", 30}, {"OT", "Exodus", 31}}}, // Day 32: OT: Exodus 29, Exodus 30, Exodus 31 | NT: 
    {33, 3, {{"OT", "Exodus", 32}, {"OT", "Exodus", 33}, {"NT", "Matthew", 23}}}, // Day 33: OT: Exodus 32, Exodus 33 | NT: Matthew 23
    {34, 4, {{"OT", "Exodus", 34}, {"OT", "Exodus", 35}, {"OT", "Exodus", 36}, {"NT", "Matthew", 24}}}, // Day 34: OT: Exodus 34, Exodus 35, Exodus 36 | NT: Matthew 24
    {35, 3, {{"OT", "Exodus", 37}, {"OT", "Exodus", 38}, {"OT", "Exodus", 39}}}, // Day 35: OT: Exodus 37, Exodus 38, Exodus 39 | NT: 
    {36, 3, {{"OT", "Exodus", 40}, {"OT", "Leviticus", 1}, {"NT", "Matthew", 25}}}, // Day 36: OT: Exodus 40, Leviticus 1 | NT: Matthew 25
    {37, 4, {{"OT", "Leviticus", 2}, {"OT", "Leviticus", 3}, {"OT", "Leviticus", 4}, {"NT", "Matthew", 26}}}, // Day 37: OT: Leviticus 2, Leviticus 3, Leviticus 4 | NT: Matthew 26
    {38, 3, {{"OT", "Leviticus", 5}, {"OT", "Leviticus", 6}, {"NT", "Matthew", 27}}}, // Day 38: OT: Leviticus 5, Leviticus 6 | NT: Matthew 27
    {39, 3, {{"OT", "Leviticus", 7}, {"OT", "Leviticus", 8}, {"OT", "Leviticus", 9}}}, // Day 39: OT: Leviticus 7, Leviticus 8, Leviticus 9 | NT: 
    {40, 3, {{"OT", "Leviticus", 10}, {"OT", "Leviticus", 11}, {"NT", "Matthew", 28}}}, // Day 40: OT: Leviticus 10, Leviticus 11 | NT: Matthew 28
    {41, 4, {{"OT", "Leviticus", 12}, {"OT", "Leviticus", 13}, {"OT", "Leviticus", 14}, {"NT", "Mark", 1}}}, // Day 41: OT: Leviticus 12, Leviticus 13, Leviticus 14 | NT: Mark 1
    {42, 2, {{"OT", "Leviticus", 15}, {"OT", "Leviticus", 16}}}, // Day 42: OT: Leviticus 15, Leviticus 16 | NT: 
    {43, 4, {{"OT", "Leviticus", 17}, {"OT", "Leviticus", 18}, {"OT", "Leviticus", 19}, {"NT", "Mark", 2}}}, // Day 43: OT: Leviticus 17, Leviticus 18, Leviticus 19 | NT: Mark 2
    {44, 3, {{"OT", "Leviticus", 20}, {"OT", "Leviticus", 21}, {"NT", "Mark", 3}}}, // Day 44: OT: Leviticus 20, Leviticus 21 | NT: Mark 3
    {45, 4, {{"OT", "Leviticus", 22}, {"OT", "Leviticus", 23}, {"OT", "Leviticus", 24}, {"NT", "Mark", 4}}}, // Day 45: OT: Leviticus 22, Leviticus 23, Leviticus 24 | NT: Mark 4
    {46, 3, {{"OT", "Leviticus", 25}, {"OT", "Leviticus", 26}, {"OT", "Leviticus", 27}}}, // Day 46: OT: Leviticus 25, Leviticus 26, Leviticus 27 | NT: 
    {47, 3, {{"OT", "Numbers", 1}, {"OT", "Numbers", 2}, {"NT", "Mark", 5}}}, // Day 47: OT: Numbers 1, Numbers 2 | NT: Mark 5
    {48, 4, {{"OT", "Numbers", 3}, {"OT", "Numbers", 4}, {"OT", "Numbers", 5}, {"NT", "Mark", 6}}}, // Day 48: OT: Numbers 3, Numbers 4, Numbers 5 | NT: Mark 6
    {49, 2, {{"OT", "Numbers", 6}, {"OT", "Numbers", 7}}}, // Day 49: OT: Numbers 6, Numbers 7 | NT: 
    {50, 4, {{"OT", "Numbers", 8}, {"OT", "Numbers", 9}, {"OT", "Numbers", 10}, {"NT", "Mark", 7}}}, // Day 50: OT: Numbers 8, Numbers 9, Numbers 10 | NT: Mark 7
    {51, 3, {{"OT", "Numbers", 11}, {"OT", "Numbers", 12}, {"NT", "Mark", 8}}}, // Day 51: OT: Numbers 11, Numbers 12 | NT: Mark 8
    {52, 4, {{"OT", "Numbers", 13}, {"OT", "Numbers", 14}, {"OT", "Numbers", 15}, {"NT", "Mark", 9}}}, // Day 52: OT: Numbers 13, Numbers 14, Numbers 15 | NT: Mark 9
    {53, 2, {{"OT", "Numbers", 16}, {"OT", "Numbers", 17}}}, // Day 53: OT: Numbers 16, Numbers 17 | NT: 
    {54, 4, {{"OT", "Numbers", 18}, {"OT", "Numbers", 19}, {"OT", "Numbers", 20}, {"NT", "Mark", 10}}}, // Day 54: OT: Numbers 18, Numbers 19, Numbers 20 | NT: Mark 10
    {55, 3, {{"OT", "Numbers", 21}, {"OT", "Numbers", 22}, {"NT", "Mark", 11}}}, // Day 55: OT: Numbers 21, Numbers 22 | NT: Mark 11
    {56, 3, {{"OT", "Numbers", 23}, {"OT", "Numbers", 24}, {"OT", "Numbers", 25}}}, // Day 56: OT: Numbers 23, Numbers 24, Numbers 25 | NT: 
    {57, 4, {{"OT", "Numbers", 26}, {"OT", "Numbers", 27}, {"OT", "Numbers", 28}, {"NT", "Mark", 12}}}, // Day 57: OT: Numbers 26, Numbers 27, Numbers 28 | NT: Mark 12
    {58, 3, {{"OT", "Numbers", 29}, {"OT", "Numbers", 30}, {"NT", "Mark", 13}}}, // Day 58: OT: Numbers 29, Numbers 30 | NT: Mark 13
    {59, 4, {{"OT", "Numbers", 31}, {"OT", "Numbers", 32}, {"OT", "Numbers", 33}, {"NT", "Mark", 14}}}, // Day 59: OT: Numbers 31, Numbers 32, Numbers 33 | NT: Mark 14
    {60, 2, {{"OT", "Numbers", 34}, {"OT", "Numbers", 35}}}, // Day 60: OT: Numbers 34, Numbers 35 | NT: 
    {61, 4, {{"OT", "Numbers", 36}, {"OT", "Deuteronomy", 1}, {"OT", "Deuteronomy", 2}, {"NT", "Mark", 15}}}, // Day 61: OT: Numbers 36, Deuteronomy 1, Deuteronomy 2 | NT: Mark 15
    {62, 3, {{"OT", "Deuteronomy", 3}, {"OT", "Deuteronomy", 4}, {"NT", "Mark", 16}}}, // Day 62: OT: Deuteronomy 3, Deuteronomy 4 | NT: Mark 16
    {63, 3, {{"OT", "Deuteronomy", 5}, {"OT", "Deuteronomy", 6}, {"OT", "Deuteronomy", 7}}}, // Day 63: OT: Deuteronomy 5, Deuteronomy 6, Deuteronomy 7 | NT: 
    {64, 3, {{"OT", "Deuteronomy", 8}, {"OT", "Deuteronomy", 9}, {"NT", "Luke", 1}}}, // Day 64: OT: Deuteronomy 8, Deuteronomy 9 | NT: Luke 1
    {65, 4, {{"OT", "Deuteronomy", 10}, {"OT", "Deuteronomy", 11}, {"OT", "Deuteronomy", 12}, {"NT", "Luke", 2}}}, // Day 65: OT: Deuteronomy 10, Deuteronomy 11, Deuteronomy 12 | NT: Luke 2
    {66, 3, {{"OT", "Deuteronomy", 13}, {"OT", "Deuteronomy", 14}, {"NT", "Luke", 3}}}, // Day 66: OT: Deuteronomy 13, Deuteronomy 14 | NT: Luke 3
    {67, 3, {{"OT", "Deuteronomy", 15}, {"OT", "Deuteronomy", 16}, {"OT", "Deuteronomy", 17}}}, // Day 67: OT: Deuteronomy 15, Deuteronomy 16, Deuteronomy 17 | NT: 
    {68, 4, {{"OT", "Deuteronomy", 18}, {"OT", "Deuteronomy", 19}, {"OT", "Deuteronomy", 20}, {"NT", "Luke", 4}}}, // Day 68: OT: Deuteronomy 18, Deuteronomy 19, Deuteronomy 20 | NT: Luke 4
    {69, 3, {{"OT", "Deuteronomy", 21}, {"OT", "Deuteronomy", 22}, {"NT", "Luke", 5}}}, // Day 69: OT: Deuteronomy 21, Deuteronomy 22 | NT: Luke 5
    {70, 3, {{"OT", "Deuteronomy", 23}, {"OT", "Deuteronomy", 24}, {"OT", "Deuteronomy", 25}}}, // Day 70: OT: Deuteronomy 23, Deuteronomy 24, Deuteronomy 25 | NT: 
    {71, 3, {{"OT", "Deuteronomy", 26}, {"OT", "Deuteronomy", 27}, {"NT", "Luke", 6}}}, // Day 71: OT: Deuteronomy 26, Deuteronomy 27 | NT: Luke 6
    {72, 4, {{"OT", "Deuteronomy", 28}, {"OT", "Deuteronomy", 29}, {"OT", "Deuteronomy", 30}, {"NT", "Luke", 7}}}, // Day 72: OT: Deuteronomy 28, Deuteronomy 29, Deuteronomy 30 | NT: Luke 7
    {73, 3, {{"OT", "Deuteronomy", 31}, {"OT", "Deuteronomy", 32}, {"NT", "Luke", 8}}}, // Day 73: OT: Deuteronomy 31, Deuteronomy 32 | NT: Luke 8
    {74, 3, {{"OT", "Deuteronomy", 33}, {"OT", "Deuteronomy", 34}, {"OT", "Joshua", 1}}}, // Day 74: OT: Deuteronomy 33, Deuteronomy 34, Joshua 1 | NT: 
    {75, 3, {{"OT", "Joshua", 2}, {"OT", "Joshua", 3}, {"NT", "Luke", 9}}}, // Day 75: OT: Joshua 2, Joshua 3 | NT: Luke 9
    {76, 4, {{"OT", "Joshua", 4}, {"OT", "Joshua", 5}, {"OT", "Joshua", 6}, {"NT", "Luke", 10}}}, // Day 76: OT: Joshua 4, Joshua 5, Joshua 6 | NT: Luke 10
    {77, 2, {{"OT", "Joshua", 7}, {"OT", "Joshua", 8}}}, // Day 77: OT: Joshua 7, Joshua 8 | NT: 
    {78, 4, {{"OT", "Joshua", 9}, {"OT", "Joshua", 10}, {"OT", "Joshua", 11}, {"NT", "Luke", 11}}}, // Day 78: OT: Joshua 9, Joshua 10, Joshua 11 | NT: Luke 11
    {79, 4, {{"OT", "Joshua", 12}, {"OT", "Joshua", 13}, {"OT", "Joshua", 14}, {"NT", "Luke", 12}}}, // Day 79: OT: Joshua 12, Joshua 13, Joshua 14 | NT: Luke 12
    {80, 2, {{"OT", "Joshua", 15}, {"OT", "Joshua", 16}}}, // Day 80: OT: Joshua 15, Joshua 16 | NT: 
    {81, 4, {{"OT", "Joshua", 17}, {"OT", "Joshua", 18}, {"OT", "Joshua", 19}, {"NT", "Luke", 13}}}, // Day 81: OT: Joshua 17, Joshua 18, Joshua 19 | NT: Luke 13
    {82, 3, {{"OT", "Joshua", 20}, {"OT", "Joshua", 21}, {"NT", "Luke", 14}}}, // Day 82: OT: Joshua 20, Joshua 21 | NT: Luke 14
    {83, 4, {{"OT", "Joshua", 22}, {"OT", "Joshua", 23}, {"OT", "Joshua", 24}, {"NT", "Luke", 15}}}, // Day 83: OT: Joshua 22, Joshua 23, Joshua 24 | NT: Luke 15
    {84, 2, {{"OT", "Judges", 1}, {"OT", "Judges", 2}}}, // Day 84: OT: Judges 1, Judges 2 | NT: 
    {85, 4, {{"OT", "Judges", 3}, {"OT", "Judges", 4}, {"OT", "Judges", 5}, {"NT", "Luke", 16}}}, // Day 85: OT: Judges 3, Judges 4, Judges 5 | NT: Luke 16
    {86, 3, {{"OT", "Judges", 6}, {"OT", "Judges", 7}, {"NT", "Luke", 17}}}, // Day 86: OT: Judges 6, Judges 7 | NT: Luke 17
    {87, 3, {{"OT", "Judges", 8}, {"OT", "Judges", 9}, {"OT", "Judges", 10}}}, // Day 87: OT: Judges 8, Judges 9, Judges 10 | NT: 
    {88, 3, {{"OT", "Judges", 11}, {"OT", "Judges", 12}, {"NT", "Luke", 18}}}, // Day 88: OT: Judges 11, Judges 12 | NT: Luke 18
    {89, 4, {{"OT", "Judges", 13}, {"OT", "Judges", 14}, {"OT", "Judges", 15}, {"NT", "Luke", 19}}}, // Day 89: OT: Judges 13, Judges 14, Judges 15 | NT: Luke 19
    {90, 4, {{"OT", "Judges", 16}, {"OT", "Judges", 17}, {"OT", "Judges", 18}, {"NT", "Luke", 20}}}, // Day 90: OT: Judges 16, Judges 17, Judges 18 | NT: Luke 20
    {91, 2, {{"OT", "Judges", 19}, {"OT", "Judges", 20}}}, // Day 91: OT: Judges 19, Judges 20 | NT: 
    {92, 4, {{"OT", "Judges", 21}, {"OT", "Ruth", 1}, {"OT", "Ruth", 2}, {"NT", "Luke", 21}}}, // Day 92: OT: Judges 21, Ruth 1, Ruth 2 | NT: Luke 21
    {93, 3, {{"OT", "Ruth", 3}, {"OT", "Ruth", 4}, {"NT", "Luke", 22}}}, // Day 93: OT: Ruth 3, Ruth 4 | NT: Luke 22
    {94, 3, {{"OT", "1 Samuel", 1}, {"OT", "1 Samuel", 2}, {"OT", "1 Samuel", 3}}}, // Day 94: OT: 1 Samuel 1, 1 Samuel 2, 1 Samuel 3 | NT: 
    {95, 3, {{"OT", "1 Samuel", 4}, {"OT", "1 Samuel", 5}, {"NT", "Luke", 23}}}, // Day 95: OT: 1 Samuel 4, 1 Samuel 5 | NT: Luke 23
    {96, 4, {{"OT", "1 Samuel", 6}, {"OT", "1 Samuel", 7}, {"OT", "1 Samuel", 8}, {"NT", "Luke", 24}}}, // Day 96: OT: 1 Samuel 6, 1 Samuel 7, 1 Samuel 8 | NT: Luke 24
    {97, 3, {{"OT", "1 Samuel", 9}, {"OT", "1 Samuel", 10}, {"NT", "John", 1}}}, // Day 97: OT: 1 Samuel 9, 1 Samuel 10 | NT: John 1
    {98, 3, {{"OT", "1 Samuel", 11}, {"OT", "1 Samuel", 12}, {"OT", "1 Samuel", 13}}}, // Day 98: OT: 1 Samuel 11, 1 Samuel 12, 1 Samuel 13 | NT: 
    {99, 3, {{"OT", "1 Samuel", 14}, {"OT", "1 Samuel", 15}, {"NT", "John", 2}}}, // Day 99: OT: 1 Samuel 14, 1 Samuel 15 | NT: John 2
    {100, 4, {{"OT", "1 Samuel", 16}, {"OT", "1 Samuel", 17}, {"OT", "1 Samuel", 18}, {"NT", "John", 3}}}, // Day 100: OT: 1 Samuel 16, 1 Samuel 17, 1 Samuel 18 | NT: John 3
    {101, 3, {{"OT", "1 Samuel", 19}, {"OT", "1 Samuel", 20}, {"OT", "1 Samuel", 21}}}, // Day 101: OT: 1 Samuel 19, 1 Samuel 20, 1 Samuel 21 | NT: 
    {102, 3, {{"OT", "1 Samuel", 22}, {"OT", "1 Samuel", 23}, {"NT", "John", 4}}}, // Day 102: OT: 1 Samuel 22, 1 Samuel 23 | NT: John 4
    {103, 4, {{"OT", "1 Samuel", 24}, {"OT", "1 Samuel", 25}, {"OT", "1 Samuel", 26}, {"NT", "John", 5}}}, // Day 103: OT: 1 Samuel 24, 1 Samuel 25, 1 Samuel 26 | NT: John 5
    {104, 3, {{"OT", "1 Samuel", 27}, {"OT", "1 Samuel", 28}, {"NT", "John", 6}}}, // Day 104: OT: 1 Samuel 27, 1 Samuel 28 | NT: John 6
    {105, 3, {{"OT", "1 Samuel", 29}, {"OT", "1 Samuel", 30}, {"OT", "1 Samuel", 31}}}, // Day 105: OT: 1 Samuel 29, 1 Samuel 30, 1 Samuel 31 | NT: 
    {106, 3, {{"OT", "2 Samuel", 1}, {"OT", "2 Samuel", 2}, {"NT", "John", 7}}}, // Day 106: OT: 2 Samuel 1, 2 Samuel 2 | NT: John 7
    {107, 4, {{"OT", "2 Samuel", 3}, {"OT", "2 Samuel", 4}, {"OT", "2 Samuel", 5}, {"NT", "John", 8}}}, // Day 107: OT: 2 Samuel 3, 2 Samuel 4, 2 Samuel 5 | NT: John 8
    {108, 2, {{"OT", "2 Samuel", 6}, {"OT", "2 Samuel", 7}}}, // Day 108: OT: 2 Samuel 6, 2 Samuel 7 | NT: 
    {109, 4, {{"OT", "2 Samuel", 8}, {"OT", "2 Samuel", 9}, {"OT", "2 Samuel", 10}, {"NT", "John", 9}}}, // Day 109: OT: 2 Samuel 8, 2 Samuel 9, 2 Samuel 10 | NT: John 9
    {110, 3, {{"OT", "2 Samuel", 11}, {"OT", "2 Samuel", 12}, {"NT", "John", 10}}}, // Day 110: OT: 2 Samuel 11, 2 Samuel 12 | NT: John 10
    {111, 4, {{"OT", "2 Samuel", 13}, {"OT", "2 Samuel", 14}, {"OT", "2 Samuel", 15}, {"NT", "John", 11}}}, // Day 111: OT: 2 Samuel 13, 2 Samuel 14, 2 Samuel 15 | NT: John 11
    {112, 3, {{"OT", "2 Samuel", 16}, {"OT", "2 Samuel", 17}, {"OT", "2 Samuel", 18}}}, // Day 112: OT: 2 Samuel 16, 2 Samuel 17, 2 Samuel 18 | NT: 
    {113, 3, {{"OT", "2 Samuel", 19}, {"OT", "2 Samuel", 20}, {"NT", "John", 12}}}, // Day 113: OT: 2 Samuel 19, 2 Samuel 20 | NT: John 12
    {114, 4, {{"OT", "2 Samuel", 21}, {"OT", "2 Samuel", 22}, {"OT", "2 Samuel", 23}, {"NT", "John", 13}}}, // Day 114: OT: 2 Samuel 21, 2 Samuel 22, 2 Samuel 23 | NT: John 13
    {115, 2, {{"OT", "2 Samuel", 24}, {"OT", "1 Kings", 1}}}, // Day 115: OT: 2 Samuel 24, 1 Kings 1 | NT: 
    {116, 4, {{"OT", "1 Kings", 2}, {"OT", "1 Kings", 3}, {"OT", "1 Kings", 4}, {"NT", "John", 14}}}, // Day 116: OT: 1 Kings 2, 1 Kings 3, 1 Kings 4 | NT: John 14
    {117, 3, {{"OT", "1 Kings", 5}, {"OT", "1 Kings", 6}, {"NT", "John", 15}}}, // Day 117: OT: 1 Kings 5, 1 Kings 6 | NT: John 15
    {118, 4, {{"OT", "1 Kings", 7}, {"OT", "1 Kings", 8}, {"OT", "1 Kings", 9}, {"NT", "John", 16}}}, // Day 118: OT: 1 Kings 7, 1 Kings 8, 1 Kings 9 | NT: John 16
    {119, 2, {{"OT", "1 Kings", 10}, {"OT", "1 Kings", 11}}}, // Day 119: OT: 1 Kings 10, 1 Kings 11 | NT: 
    {120, 4, {{"OT", "1 Kings", 12}, {"OT", "1 Kings", 13}, {"OT", "1 Kings", 14}, {"NT", "John", 17}}}, // Day 120: OT: 1 Kings 12, 1 Kings 13, 1 Kings 14 | NT: John 17
    {121, 3, {{"OT", "1 Kings", 15}, {"OT", "1 Kings", 16}, {"NT", "John", 18}}}, // Day 121: OT: 1 Kings 15, 1 Kings 16 | NT: John 18
    {122, 3, {{"OT", "1 Kings", 17}, {"OT", "1 Kings", 18}, {"OT", "1 Kings", 19}}}, // Day 122: OT: 1 Kings 17, 1 Kings 18, 1 Kings 19 | NT: 
    {123, 4, {{"OT", "1 Kings", 20}, {"OT", "1 Kings", 21}, {"OT", "1 Kings", 22}, {"NT", "John", 19}}}, // Day 123: OT: 1 Kings 20, 1 Kings 21, 1 Kings 22 | NT: John 19
    {124, 3, {{"OT", "2 Kings", 1}, {"OT", "2 Kings", 2}, {"NT", "John", 20}}}, // Day 124: OT: 2 Kings 1, 2 Kings 2 | NT: John 20
    {125, 4, {{"OT", "2 Kings", 3}, {"OT", "2 Kings", 4}, {"OT", "2 Kings", 5}, {"NT", "John", 21}}}, // Day 125: OT: 2 Kings 3, 2 Kings 4, 2 Kings 5 | NT: John 21
    {126, 2, {{"OT", "2 Kings", 6}, {"OT", "2 Kings", 7}}}, // Day 126: OT: 2 Kings 6, 2 Kings 7 | NT: 
    {127, 4, {{"OT", "2 Kings", 8}, {"OT", "2 Kings", 9}, {"OT", "2 Kings", 10}, {"NT", "Acts", 1}}}, // Day 127: OT: 2 Kings 8, 2 Kings 9, 2 Kings 10 | NT: Acts 1
    {128, 3, {{"OT", "2 Kings", 11}, {"OT", "2 Kings", 12}, {"NT", "Acts", 2}}}, // Day 128: OT: 2 Kings 11, 2 Kings 12 | NT: Acts 2
    {129, 3, {{"OT", "2 Kings", 13}, {"OT", "2 Kings", 14}, {"OT", "2 Kings", 15}}}, // Day 129: OT: 2 Kings 13, 2 Kings 14, 2 Kings 15 | NT: 
    {130, 3, {{"OT", "2 Kings", 16}, {"OT", "2 Kings", 17}, {"NT", "Acts", 3}}}, // Day 130: OT: 2 Kings 16, 2 Kings 17 | NT: Acts 3
    {131, 4, {{"OT", "2 Kings", 18}, {"OT", "2 Kings", 19}, {"OT", "2 Kings", 20}, {"NT", "Acts", 4}}}, // Day 131: OT: 2 Kings 18, 2 Kings 19, 2 Kings 20 | NT: Acts 4
    {132, 3, {{"OT", "2 Kings", 21}, {"OT", "2 Kings", 22}, {"NT", "Acts", 5}}}, // Day 132: OT: 2 Kings 21, 2 Kings 22 | NT: Acts 5
    {133, 3, {{"OT", "2 Kings", 23}, {"OT", "2 Kings", 24}, {"OT", "2 Kings", 25}}}, // Day 133: OT: 2 Kings 23, 2 Kings 24, 2 Kings 25 | NT: 
    {134, 4, {{"OT", "1 Chronicles", 1}, {"OT", "1 Chronicles", 2}, {"OT", "1 Chronicles", 3}, {"NT", "Acts", 6}}}, // Day 134: OT: 1 Chronicles 1, 1 Chronicles 2, 1 Chronicles 3 | NT: Acts 6
    {135, 3, {{"OT", "1 Chronicles", 4}, {"OT", "1 Chronicles", 5}, {"NT", "Acts", 7}}}, // Day 135: OT: 1 Chronicles 4, 1 Chronicles 5 | NT: Acts 7
    {136, 3, {{"OT", "1 Chronicles", 6}, {"OT", "1 Chronicles", 7}, {"OT", "1 Chronicles", 8}}}, // Day 136: OT: 1 Chronicles 6, 1 Chronicles 7, 1 Chronicles 8 | NT: 
    {137, 3, {{"OT", "1 Chronicles", 9}, {"OT", "1 Chronicles", 10}, {"NT", "Acts", 8}}}, // Day 137: OT: 1 Chronicles 9, 1 Chronicles 10 | NT: Acts 8
    {138, 4, {{"OT", "1 Chronicles", 11}, {"OT", "1 Chronicles", 12}, {"OT", "1 Chronicles", 13}, {"NT", "Acts", 9}}}, // Day 138: OT: 1 Chronicles 11, 1 Chronicles 12, 1 Chronicles 13 | NT: Acts 9
    {139, 3, {{"OT", "1 Chronicles", 14}, {"OT", "1 Chronicles", 15}, {"NT", "Acts", 10}}}, // Day 139: OT: 1 Chronicles 14, 1 Chronicles 15 | NT: Acts 10
    {140, 3, {{"OT", "1 Chronicles", 16}, {"OT", "1 Chronicles", 17}, {"OT", "1 Chronicles", 18}}}, // Day 140: OT: 1 Chronicles 16, 1 Chronicles 17, 1 Chronicles 18 | NT: 
    {141, 3, {{"OT", "1 Chronicles", 19}, {"OT", "1 Chronicles", 20}, {"NT", "Acts", 11}}}, // Day 141: OT: 1 Chronicles 19, 1 Chronicles 20 | NT: Acts 11
    {142, 4, {{"OT", "1 Chronicles", 21}, {"OT", "1 Chronicles", 22}, {"OT", "1 Chronicles", 23}, {"NT", "Acts", 12}}}, // Day 142: OT: 1 Chronicles 21, 1 Chronicles 22, 1 Chronicles 23 | NT: Acts 12
    {143, 2, {{"OT", "1 Chronicles", 24}, {"OT", "1 Chronicles", 25}}}, // Day 143: OT: 1 Chronicles 24, 1 Chronicles 25 | NT: 
    {144, 4, {{"OT", "1 Chronicles", 26}, {"OT", "1 Chronicles", 27}, {"OT", "1 Chronicles", 28}, {"NT", "Acts", 13}}}, // Day 144: OT: 1 Chronicles 26, 1 Chronicles 27, 1 Chronicles 28 | NT: Acts 13
    {145, 4, {{"OT", "1 Chronicles", 29}, {"OT", "2 Chronicles", 1}, {"OT", "2 Chronicles", 2}, {"NT", "Acts", 14}}}, // Day 145: OT: 1 Chronicles 29, 2 Chronicles 1, 2 Chronicles 2 | NT: Acts 14
    {146, 3, {{"OT", "2 Chronicles", 3}, {"OT", "2 Chronicles", 4}, {"NT", "Acts", 15}}}, // Day 146: OT: 2 Chronicles 3, 2 Chronicles 4 | NT: Acts 15
    {147, 3, {{"OT", "2 Chronicles", 5}, {"OT", "2 Chronicles", 6}, {"OT", "2 Chronicles", 7}}}, // Day 147: OT: 2 Chronicles 5, 2 Chronicles 6, 2 Chronicles 7 | NT: 
    {148, 3, {{"OT", "2 Chronicles", 8}, {"OT", "2 Chronicles", 9}, {"NT", "Acts", 16}}}, // Day 148: OT: 2 Chronicles 8, 2 Chronicles 9 | NT: Acts 16
    {149, 4, {{"OT", "2 Chronicles", 10}, {"OT", "2 Chronicles", 11}, {"OT", "2 Chronicles", 12}, {"NT", "Acts", 17}}}, // Day 149: OT: 2 Chronicles 10, 2 Chronicles 11, 2 Chronicles 12 | NT: Acts 17
    {150, 2, {{"OT", "2 Chronicles", 13}, {"OT", "2 Chronicles", 14}}}, // Day 150: OT: 2 Chronicles 13, 2 Chronicles 14 | NT: 
    {151, 4, {{"OT", "2 Chronicles", 15}, {"OT", "2 Chronicles", 16}, {"OT", "2 Chronicles", 17}, {"NT", "Acts", 18}}}, // Day 151: OT: 2 Chronicles 15, 2 Chronicles 16, 2 Chronicles 17 | NT: Acts 18
    {152, 3, {{"OT", "2 Chronicles", 18}, {"OT", "2 Chronicles", 19}, {"NT", "Acts", 19}}}, // Day 152: OT: 2 Chronicles 18, 2 Chronicles 19 | NT: Acts 19
    {153, 3, {{"OT", "2 Chronicles", 20}, {"OT", "2 Chronicles", 21}, {"OT", "2 Chronicles", 22}}}, // Day 153: OT: 2 Chronicles 20, 2 Chronicles 21, 2 Chronicles 22 | NT: 
    {154, 3, {{"OT", "2 Chronicles", 23}, {"OT", "2 Chronicles", 24}, {"NT", "Acts", 20}}}, // Day 154: OT: 2 Chronicles 23, 2 Chronicles 24 | NT: Acts 20
    {155, 4, {{"OT", "2 Chronicles", 25}, {"OT", "2 Chronicles", 26}, {"OT", "2 Chronicles", 27}, {"NT", "Acts", 21}}}, // Day 155: OT: 2 Chronicles 25, 2 Chronicles 26, 2 Chronicles 27 | NT: Acts 21
    {156, 4, {{"OT", "2 Chronicles", 28}, {"OT", "2 Chronicles", 29}, {"OT", "2 Chronicles", 30}, {"NT", "Acts", 22}}}, // Day 156: OT: 2 Chronicles 28, 2 Chronicles 29, 2 Chronicles 30 | NT: Acts 22
    {157, 2, {{"OT", "2 Chronicles", 31}, {"OT", "2 Chronicles", 32}}}, // Day 157: OT: 2 Chronicles 31, 2 Chronicles 32 | NT: 
    {158, 4, {{"OT", "2 Chronicles", 33}, {"OT", "2 Chronicles", 34}, {"OT", "2 Chronicles", 35}, {"NT", "Acts", 23}}}, // Day 158: OT: 2 Chronicles 33, 2 Chronicles 34, 2 Chronicles 35 | NT: Acts 23
    {159, 3, {{"OT", "2 Chronicles", 36}, {"OT", "Ezra", 1}, {"NT", "Acts", 24}}}, // Day 159: OT: 2 Chronicles 36, Ezra 1 | NT: Acts 24
    {160, 3, {{"OT", "Ezra", 2}, {"OT", "Ezra", 3}, {"OT", "Ezra", 4}}}, // Day 160: OT: Ezra 2, Ezra 3, Ezra 4 | NT: 
    {161, 3, {{"OT", "Ezra", 5}, {"OT", "Ezra", 6}, {"NT", "Acts", 25}}}, // Day 161: OT: Ezra 5, Ezra 6 | NT: Acts 25
    {162, 4, {{"OT", "Ezra", 7}, {"OT", "Ezra", 8}, {"OT", "Ezra", 9}, {"NT", "Acts", 26}}}, // Day 162: OT: Ezra 7, Ezra 8, Ezra 9 | NT: Acts 26
    {163, 3, {{"OT", "Ezra", 10}, {"OT", "Nehemiah", 1}, {"NT", "Acts", 27}}}, // Day 163: OT: Ezra 10, Nehemiah 1 | NT: Acts 27
    {164, 3, {{"OT", "Nehemiah", 2}, {"OT", "Nehemiah", 3}, {"OT", "Nehemiah", 4}}}, // Day 164: OT: Nehemiah 2, Nehemiah 3, Nehemiah 4 | NT: 
    {165, 3, {{"OT", "Nehemiah", 5}, {"OT", "Nehemiah", 6}, {"NT", "Acts", 28}}}, // Day 165: OT: Nehemiah 5, Nehemiah 6 | NT: Acts 28
    {166, 4, {{"OT", "Nehemiah", 7}, {"OT", "Nehemiah", 8}, {"OT", "Nehemiah", 9}, {"NT", "Romans", 1}}}, // Day 166: OT: Nehemiah 7, Nehemiah 8, Nehemiah 9 | NT: Romans 1
    {167, 3, {{"OT", "Nehemiah", 10}, {"OT", "Nehemiah", 11}, {"OT", "Nehemiah", 12}}}, // Day 167: OT: Nehemiah 10, Nehemiah 11, Nehemiah 12 | NT: 
    {168, 3, {{"OT", "Nehemiah", 13}, {"OT", "Esther", 1}, {"NT", "Romans", 2}}}, // Day 168: OT: Nehemiah 13, Esther 1 | NT: Romans 2
    {169, 4, {{"OT", "Esther", 2}, {"OT", "Esther", 3}, {"OT", "Esther", 4}, {"NT", "Romans", 3}}}, // Day 169: OT: Esther 2, Esther 3, Esther 4 | NT: Romans 3
    {170, 3, {{"OT", "Esther", 5}, {"OT", "Esther", 6}, {"NT", "Romans", 4}}}, // Day 170: OT: Esther 5, Esther 6 | NT: Romans 4
    {171, 3, {{"OT", "Esther", 7}, {"OT", "Esther", 8}, {"OT", "Esther", 9}}}, // Day 171: OT: Esther 7, Esther 8, Esther 9 | NT: 
    {172, 3, {{"OT", "Esther", 10}, {"OT", "Job", 1}, {"NT", "Romans", 5}}}, // Day 172: OT: Esther 10, Job 1 | NT: Romans 5
    {173, 4, {{"OT", "Job", 2}, {"OT", "Job", 3}, {"OT", "Job", 4}, {"NT", "Romans", 6}}}, // Day 173: OT: Job 2, Job 3, Job 4 | NT: Romans 6
    {174, 2, {{"OT", "Job", 5}, {"OT", "Job", 6}}}, // Day 174: OT: Job 5, Job 6 | NT: 
    {175, 4, {{"OT", "Job", 7}, {"OT", "Job", 8}, {"OT", "Job", 9}, {"NT", "Romans", 7}}}, // Day 175: OT: Job 7, Job 8, Job 9 | NT: Romans 7
    {176, 3, {{"OT", "Job", 10}, {"OT", "Job", 11}, {"NT", "Romans", 8}}}, // Day 176: OT: Job 10, Job 11 | NT: Romans 8
    {177, 4, {{"OT", "Job", 12}, {"OT", "Job", 13}, {"OT", "Job", 14}, {"NT", "Romans", 9}}}, // Day 177: OT: Job 12, Job 13, Job 14 | NT: Romans 9
    {178, 3, {{"OT", "Job", 15}, {"OT", "Job", 16}, {"OT", "Job", 17}}}, // Day 178: OT: Job 15, Job 16, Job 17 | NT: 
    {179, 3, {{"OT", "Job", 18}, {"OT", "Job", 19}, {"NT", "Romans", 10}}}, // Day 179: OT: Job 18, Job 19 | NT: Romans 10
    {180, 4, {{"OT", "Job", 20}, {"OT", "Job", 21}, {"OT", "Job", 22}, {"NT", "Romans", 11}}}, // Day 180: OT: Job 20, Job 21, Job 22 | NT: Romans 11
    {181, 2, {{"OT", "Job", 23}, {"OT", "Job", 24}}}, // Day 181: OT: Job 23, Job 24 | NT: 
    {182, 4, {{"OT", "Job", 25}, {"OT", "Job", 26}, {"OT", "Job", 27}, {"NT", "Romans", 12}}}, // Day 182: OT: Job 25, Job 26, Job 27 | NT: Romans 12
    {183, 3, {{"OT", "Job", 28}, {"OT", "Job", 29}, {"NT", "Romans", 13}}}, // Day 183: OT: Job 28, Job 29 | NT: Romans 13
    {184, 4, {{"OT", "Job", 30}, {"OT", "Job", 31}, {"OT", "Job", 32}, {"NT", "Romans", 14}}}, // Day 184: OT: Job 30, Job 31, Job 32 | NT: Romans 14
    {185, 2, {{"OT", "Job", 33}, {"OT", "Job", 34}}}, // Day 185: OT: Job 33, Job 34 | NT: 
    {186, 4, {{"OT", "Job", 35}, {"OT", "Job", 36}, {"OT", "Job", 37}, {"NT", "Romans", 15}}}, // Day 186: OT: Job 35, Job 36, Job 37 | NT: Romans 15
    {187, 3, {{"OT", "Job", 38}, {"OT", "Job", 39}, {"NT", "Romans", 16}}}, // Day 187: OT: Job 38, Job 39 | NT: Romans 16
    {188, 3, {{"OT", "Job", 40}, {"OT", "Job", 41}, {"OT", "Job", 42}}}, // Day 188: OT: Job 40, Job 41, Job 42 | NT: 
    {189, 4, {{"OT", "Psalm", 1}, {"OT", "Psalm", 2}, {"OT", "Psalm", 3}, {"NT", "1 Corinthians", 1}}}, // Day 189: OT: Psalm 1, Psalm 2, Psalm 3 | NT: 1 Corinthians 1
    {190, 3, {{"OT", "Psalm", 4}, {"OT", "Psalm", 5}, {"NT", "1 Corinthians", 2}}}, // Day 190: OT: Psalm 4, Psalm 5 | NT: 1 Corinthians 2
    {191, 4, {{"OT", "Psalm", 6}, {"OT", "Psalm", 7}, {"OT", "Psalm", 8}, {"NT", "1 Corinthians", 3}}}, // Day 191: OT: Psalm 6, Psalm 7, Psalm 8 | NT: 1 Corinthians 3
    {192, 2, {{"OT", "Psalm", 9}, {"OT", "Psalm", 10}}}, // Day 192: OT: Psalm 9, Psalm 10 | NT: 
    {193, 4, {{"OT", "Psalm", 11}, {"OT", "Psalm", 12}, {"OT", "Psalm", 13}, {"NT", "1 Corinthians", 4}}}, // Day 193: OT: Psalm 11, Psalm 12, Psalm 13 | NT: 1 Corinthians 4
    {194, 3, {{"OT", "Psalm", 14}, {"OT", "Psalm", 15}, {"NT", "1 Corinthians", 5}}}, // Day 194: OT: Psalm 14, Psalm 15 | NT: 1 Corinthians 5
    {195, 3, {{"OT", "Psalm", 16}, {"OT", "Psalm", 17}, {"OT", "Psalm", 18}}}, // Day 195: OT: Psalm 16, Psalm 17, Psalm 18 | NT: 
    {196, 3, {{"OT", "Psalm", 19}, {"OT", "Psalm", 20}, {"NT", "1 Corinthians", 6}}}, // Day 196: OT: Psalm 19, Psalm 20 | NT: 1 Corinthians 6
    {197, 4, {{"OT", "Psalm", 21}, {"OT", "Psalm", 22}, {"OT", "Psalm", 23}, {"NT", "1 Corinthians", 7}}}, // Day 197: OT: Psalm 21, Psalm 22, Psalm 23 | NT: 1 Corinthians 7
    {198, 3, {{"OT", "Psalm", 24}, {"OT", "Psalm", 25}, {"NT", "1 Corinthians", 8}}}, // Day 198: OT: Psalm 24, Psalm 25 | NT: 1 Corinthians 8
    {199, 3, {{"OT", "Psalm", 26}, {"OT", "Psalm", 27}, {"OT", "Psalm", 28}}}, // Day 199: OT: Psalm 26, Psalm 27, Psalm 28 | NT: 
    {200, 4, {{"OT", "Psalm", 29}, {"OT", "Psalm", 30}, {"OT", "Psalm", 31}, {"NT", "1 Corinthians", 9}}}, // Day 200: OT: Psalm 29, Psalm 30, Psalm 31 | NT: 1 Corinthians 9
    {201, 3, {{"OT", "Psalm", 32}, {"OT", "Psalm", 33}, {"NT", "1 Corinthians", 10}}}, // Day 201: OT: Psalm 32, Psalm 33 | NT: 1 Corinthians 10
    {202, 3, {{"OT", "Psalm", 34}, {"OT", "Psalm", 35}, {"OT", "Psalm", 36}}}, // Day 202: OT: Psalm 34, Psalm 35, Psalm 36 | NT: 
    {203, 3, {{"OT", "Psalm", 37}, {"OT", "Psalm", 38}, {"NT", "1 Corinthians", 11}}}, // Day 203: OT: Psalm 37, Psalm 38 | NT: 1 Corinthians 11
    {204, 4, {{"OT", "Psalm", 39}, {"OT", "Psalm", 40}, {"OT", "Psalm", 41}, {"NT", "1 Corinthians", 12}}}, // Day 204: OT: Psalm 39, Psalm 40, Psalm 41 | NT: 1 Corinthians 12
    {205, 3, {{"OT", "Psalm", 42}, {"OT", "Psalm", 43}, {"NT", "1 Corinthians", 13}}}, // Day 205: OT: Psalm 42, Psalm 43 | NT: 1 Corinthians 13
    {206, 3, {{"OT", "Psalm", 44}, {"OT", "Psalm", 45}, {"OT", "Psalm", 46}}}, // Day 206: OT: Psalm 44, Psalm 45, Psalm 46 | NT: 
    {207, 3, {{"OT", "Psalm", 47}, {"OT", "Psalm", 48}, {"NT", "1 Corinthians", 14}}}, // Day 207: OT: Psalm 47, Psalm 48 | NT: 1 Corinthians 14
    {208, 4, {{"OT", "Psalm", 49}, {"OT", "Psalm", 50}, {"OT", "Psalm", 51}, {"NT", "1 Corinthians", 15}}}, // Day 208: OT: Psalm 49, Psalm 50, Psalm 51 | NT: 1 Corinthians 15
    {209, 2, {{"OT", "Psalm", 52}, {"OT", "Psalm", 53}}}, // Day 209: OT: Psalm 52, Psalm 53 | NT: 
    {210, 4, {{"OT", "Psalm", 54}, {"OT", "Psalm", 55}, {"OT", "Psalm", 56}, {"NT", "1 Corinthians", 16}}}, // Day 210: OT: Psalm 54, Psalm 55, Psalm 56 | NT: 1 Corinthians 16
    {211, 4, {{"OT", "Psalm", 57}, {"OT", "Psalm", 58}, {"OT", "Psalm", 59}, {"NT", "2 Corinthians", 1}}}, // Day 211: OT: Psalm 57, Psalm 58, Psalm 59 | NT: 2 Corinthians 1
    {212, 3, {{"OT", "Psalm", 60}, {"OT", "Psalm", 61}, {"NT", "2 Corinthians", 2}}}, // Day 212: OT: Psalm 60, Psalm 61 | NT: 2 Corinthians 2
    {213, 3, {{"OT", "Psalm", 62}, {"OT", "Psalm", 63}, {"OT", "Psalm", 64}}}, // Day 213: OT: Psalm 62, Psalm 63, Psalm 64 | NT: 
    {214, 3, {{"OT", "Psalm", 65}, {"OT", "Psalm", 66}, {"NT", "2 Corinthians", 3}}}, // Day 214: OT: Psalm 65, Psalm 66 | NT: 2 Corinthians 3
    {215, 4, {{"OT", "Psalm", 67}, {"OT", "Psalm", 68}, {"OT", "Psalm", 69}, {"NT", "2 Corinthians", 4}}}, // Day 215: OT: Psalm 67, Psalm 68, Psalm 69 | NT: 2 Corinthians 4
    {216, 2, {{"OT", "Psalm", 70}, {"OT", "Psalm", 71}}}, // Day 216: OT: Psalm 70, Psalm 71 | NT: 
    {217, 4, {{"OT", "Psalm", 72}, {"OT", "Psalm", 73}, {"OT", "Psalm", 74}, {"NT", "2 Corinthians", 5}}}, // Day 217: OT: Psalm 72, Psalm 73, Psalm 74 | NT: 2 Corinthians 5
    {218, 3, {{"OT", "Psalm", 75}, {"OT", "Psalm", 76}, {"NT", "2 Corinthians", 6}}}, // Day 218: OT: Psalm 75, Psalm 76 | NT: 2 Corinthians 6
    {219, 4, {{"OT", "Psalm", 77}, {"OT", "Psalm", 78}, {"OT", "Psalm", 79}, {"NT", "2 Corinthians", 7}}}, // Day 219: OT: Psalm 77, Psalm 78, Psalm 79 | NT: 2 Corinthians 7
    {220, 2, {{"OT", "Psalm", 80}, {"OT", "Psalm", 81}}}, // Day 220: OT: Psalm 80, Psalm 81 | NT: 
    {221, 4, {{"OT", "Psalm", 82}, {"OT", "Psalm", 83}, {"OT", "Psalm", 84}, {"NT", "2 Corinthians", 8}}}, // Day 221: OT: Psalm 82, Psalm 83, Psalm 84 | NT: 2 Corinthians 8
    {222, 4, {{"OT", "Psalm", 85}, {"OT", "Psalm", 86}, {"OT", "Psalm", 87}, {"NT", "2 Corinthians", 9}}}, // Day 222: OT: Psalm 85, Psalm 86, Psalm 87 | NT: 2 Corinthians 9
    {223, 2, {{"OT", "Psalm", 88}, {"OT", "Psalm", 89}}}, // Day 223: OT: Psalm 88, Psalm 89 | NT: 
    {224, 4, {{"OT", "Psalm", 90}, {"OT", "Psalm", 91}, {"OT", "Psalm", 92}, {"NT", "2 Corinthians", 10}}}, // Day 224: OT: Psalm 90, Psalm 91, Psalm 92 | NT: 2 Corinthians 10
    {225, 3, {{"OT", "Psalm", 93}, {"OT", "Psalm", 94}, {"NT", "2 Corinthians", 11}}}, // Day 225: OT: Psalm 93, Psalm 94 | NT: 2 Corinthians 11
    {226, 3, {{"OT", "Psalm", 95}, {"OT", "Psalm", 96}, {"OT", "Psalm", 97}}}, // Day 226: OT: Psalm 95, Psalm 96, Psalm 97 | NT: 
    {227, 3, {{"OT", "Psalm", 98}, {"OT", "Psalm", 99}, {"NT", "2 Corinthians", 12}}}, // Day 227: OT: Psalm 98, Psalm 99 | NT: 2 Corinthians 12
    {228, 4, {{"OT", "Psalm", 100}, {"OT", "Psalm", 101}, {"OT", "Psalm", 102}, {"NT", "2 Corinthians", 13}}}, // Day 228: OT: Psalm 100, Psalm 101, Psalm 102 | NT: 2 Corinthians 13
    {229, 3, {{"OT", "Psalm", 103}, {"OT", "Psalm", 104}, {"NT", "Galatians", 1}}}, // Day 229: OT: Psalm 103, Psalm 104 | NT: Galatians 1
    {230, 3, {{"OT", "Psalm", 105}, {"OT", "Psalm", 106}, {"OT", "Psalm", 107}}}, // Day 230: OT: Psalm 105, Psalm 106, Psalm 107 | NT: 
    {231, 3, {{"OT", "Psalm", 108}, {"OT", "Psalm", 109}, {"NT", "Galatians", 2}}}, // Day 231: OT: Psalm 108, Psalm 109 | NT: Galatians 2
    {232, 4, {{"OT", "Psalm", 110}, {"OT", "Psalm", 111}, {"OT", "Psalm", 112}, {"NT", "Galatians", 3}}}, // Day 232: OT: Psalm 110, Psalm 111, Psalm 112 | NT: Galatians 3
    {233, 3, {{"OT", "Psalm", 113}, {"OT", "Psalm", 114}, {"OT", "Psalm", 115}}}, // Day 233: OT: Psalm 113, Psalm 114, Psalm 115 | NT: 
    {234, 3, {{"OT", "Psalm", 116}, {"OT", "Psalm", 117}, {"NT", "Galatians", 4}}}, // Day 234: OT: Psalm 116, Psalm 117 | NT: Galatians 4
    {235, 4, {{"OT", "Psalm", 118}, {"OT", "Psalm", 119}, {"OT", "Psalm", 120}, {"NT", "Galatians", 5}}}, // Day 235: OT: Psalm 118, Psalm 119, Psalm 120 | NT: Galatians 5
    {236, 3, {{"OT", "Psalm", 121}, {"OT", "Psalm", 122}, {"NT", "Galatians", 6}}}, // Day 236: OT: Psalm 121, Psalm 122 | NT: Galatians 6
    {237, 3, {{"OT", "Psalm", 123}, {"OT", "Psalm", 124}, {"OT", "Psalm", 125}}}, // Day 237: OT: Psalm 123, Psalm 124, Psalm 125 | NT: 
    {238, 3, {{"OT", "Psalm", 126}, {"OT", "Psalm", 127}, {"NT", "Ephesians", 1}}}, // Day 238: OT: Psalm 126, Psalm 127 | NT: Ephesians 1
    {239, 4, {{"OT", "Psalm", 128}, {"OT", "Psalm", 129}, {"OT", "Psalm", 130}, {"NT", "Ephesians", 2}}}, // Day 239: OT: Psalm 128, Psalm 129, Psalm 130 | NT: Ephesians 2
    {240, 2, {{"OT", "Psalm", 131}, {"OT", "Psalm", 132}}}, // Day 240: OT: Psalm 131, Psalm 132 | NT: 
    {241, 4, {{"OT", "Psalm", 133}, {"OT", "Psalm", 134}, {"OT", "Psalm", 135}, {"NT", "Ephesians", 3}}}, // Day 241: OT: Psalm 133, Psalm 134, Psalm 135 | NT: Ephesians 3
    {242, 3, {{"OT", "Psalm", 136}, {"OT", "Psalm", 137}, {"NT", "Ephesians", 4}}}, // Day 242: OT: Psalm 136, Psalm 137 | NT: Ephesians 4
    {243, 4, {{"OT", "Psalm", 138}, {"OT", "Psalm", 139}, {"OT", "Psalm", 140}, {"NT", "Ephesians", 5}}}, // Day 243: OT: Psalm 138, Psalm 139, Psalm 140 | NT: Ephesians 5
    {244, 3, {{"OT", "Psalm", 141}, {"OT", "Psalm", 142}, {"OT", "Psalm", 143}}}, // Day 244: OT: Psalm 141, Psalm 142, Psalm 143 | NT: 
    {245, 3, {{"OT", "Psalm", 144}, {"OT", "Psalm", 145}, {"NT", "Ephesians", 6}}}, // Day 245: OT: Psalm 144, Psalm 145 | NT: Ephesians 6
    {246, 4, {{"OT", "Psalm", 146}, {"OT", "Psalm", 147}, {"OT", "Psalm", 148}, {"NT", "Philippians", 1}}}, // Day 246: OT: Psalm 146, Psalm 147, Psalm 148 | NT: Philippians 1
    {247, 2, {{"OT", "Psalm", 149}, {"OT", "Psalm", 150}}}, // Day 247: OT: Psalm 149, Psalm 150 | NT: 
    {248, 4, {{"OT", "Proverbs", 1}, {"OT", "Proverbs", 2}, {"OT", "Proverbs", 3}, {"NT", "Philippians", 2}}}, // Day 248: OT: Proverbs 1, Proverbs 2, Proverbs 3 | NT: Philippians 2
    {249, 3, {{"OT", "Proverbs", 4}, {"OT", "Proverbs", 5}, {"NT", "Philippians", 3}}}, // Day 249: OT: Proverbs 4, Proverbs 5 | NT: Philippians 3
    {250, 4, {{"OT", "Proverbs", 6}, {"OT", "Proverbs", 7}, {"OT", "Proverbs", 8}, {"NT", "Philippians", 4}}}, // Day 250: OT: Proverbs 6, Proverbs 7, Proverbs 8 | NT: Philippians 4
    {251, 2, {{"OT", "Proverbs", 9}, {"OT", "Proverbs", 10}}}, // Day 251: OT: Proverbs 9, Proverbs 10 | NT: 
    {252, 4, {{"OT", "Proverbs", 11}, {"OT", "Proverbs", 12}, {"OT", "Proverbs", 13}, {"NT", "Colossians", 1}}}, // Day 252: OT: Proverbs 11, Proverbs 12, Proverbs 13 | NT: Colossians 1
    {253, 3, {{"OT", "Proverbs", 14}, {"OT", "Proverbs", 15}, {"NT", "Colossians", 2}}}, // Day 253: OT: Proverbs 14, Proverbs 15 | NT: Colossians 2
    {254, 3, {{"OT", "Proverbs", 16}, {"OT", "Proverbs", 17}, {"OT", "Proverbs", 18}}}, // Day 254: OT: Proverbs 16, Proverbs 17, Proverbs 18 | NT: 
    {255, 4, {{"OT", "Proverbs", 19}, {"OT", "Proverbs", 20}, {"OT", "Proverbs", 21}, {"NT", "Colossians", 3}}}, // Day 255: OT: Proverbs 19, Proverbs 20, Proverbs 21 | NT: Colossians 3
    {256, 3, {{"OT", "Proverbs", 22}, {"OT", "Proverbs", 23}, {"NT", "Colossians", 4}}}, // Day 256: OT: Proverbs 22, Proverbs 23 | NT: Colossians 4
    {257, 4, {{"OT", "Proverbs", 24}, {"OT", "Proverbs", 25}, {"OT", "Proverbs", 26}, {"NT", "1 Thessalonians", 1}}}, // Day 257: OT: Proverbs 24, Proverbs 25, Proverbs 26 | NT: 1 Thessalonians 1
    {258, 2, {{"OT", "Proverbs", 27}, {"OT", "Proverbs", 28}}}, // Day 258: OT: Proverbs 27, Proverbs 28 | NT: 
    {259, 4, {{"OT", "Proverbs", 29}, {"OT", "Proverbs", 30}, {"OT", "Proverbs", 31}, {"NT", "1 Thessalonians", 2}}}, // Day 259: OT: Proverbs 29, Proverbs 30, Proverbs 31 | NT: 1 Thessalonians 2
    {260, 3, {{"OT", "Ecclesiastes", 1}, {"OT", "Ecclesiastes", 2}, {"NT", "1 Thessalonians", 3}}}, // Day 260: OT: Ecclesiastes 1, Ecclesiastes 2 | NT: 1 Thessalonians 3
    {261, 3, {{"OT", "Ecclesiastes", 3}, {"OT", "Ecclesiastes", 4}, {"OT", "Ecclesiastes", 5}}}, // Day 261: OT: Ecclesiastes 3, Ecclesiastes 4, Ecclesiastes 5 | NT: 
    {262, 3, {{"OT", "Ecclesiastes", 6}, {"OT", "Ecclesiastes", 7}, {"NT", "1 Thessalonians", 4}}}, // Day 262: OT: Ecclesiastes 6, Ecclesiastes 7 | NT: 1 Thessalonians 4
    {263, 4, {{"OT", "Ecclesiastes", 8}, {"OT", "Ecclesiastes", 9}, {"OT", "Ecclesiastes", 10}, {"NT", "1 Thessalonians", 5}}}, // Day 263: OT: Ecclesiastes 8, Ecclesiastes 9, Ecclesiastes 10 | NT: 1 Thessalonians 5
    {264, 3, {{"OT", "Ecclesiastes", 11}, {"OT", "Ecclesiastes", 12}, {"NT", "2 Thessalonians", 1}}}, // Day 264: OT: Ecclesiastes 11, Ecclesiastes 12 | NT: 2 Thessalonians 1
    {265, 3, {{"OT", "Song of Solomon", 1}, {"OT", "Song of Solomon", 2}, {"OT", "Song of Solomon", 3}}}, // Day 265: OT: Song of Solomon 1, Song of Solomon 2, Song of Solomon 3 | NT: 
    {266, 4, {{"OT", "Song of Solomon", 4}, {"OT", "Song of Solomon", 5}, {"OT", "Song of Solomon", 6}, {"NT", "2 Thessalonians", 2}}}, // Day 266: OT: Song of Solomon 4, Song of Solomon 5, Song of Solomon 6 | NT: 2 Thessalonians 2
    {267, 3, {{"OT", "Song of Solomon", 7}, {"OT", "Song of Solomon", 8}, {"NT", "2 Thessalonians", 3}}}, // Day 267: OT: Song of Solomon 7, Song of Solomon 8 | NT: 2 Thessalonians 3
    {268, 3, {{"OT", "Isaiah", 1}, {"OT", "Isaiah", 2}, {"OT", "Isaiah", 3}}}, // Day 268: OT: Isaiah 1, Isaiah 2, Isaiah 3 | NT: 
    {269, 3, {{"OT", "Isaiah", 4}, {"OT", "Isaiah", 5}, {"NT", "1 Timothy", 1}}}, // Day 269: OT: Isaiah 4, Isaiah 5 | NT: 1 Timothy 1
    {270, 4, {{"OT", "Isaiah", 6}, {"OT", "Isaiah", 7}, {"OT", "Isaiah", 8}, {"NT", "1 Timothy", 2}}}, // Day 270: OT: Isaiah 6, Isaiah 7, Isaiah 8 | NT: 1 Timothy 2
    {271, 3, {{"OT", "Isaiah", 9}, {"OT", "Isaiah", 10}, {"NT", "1 Timothy", 3}}}, // Day 271: OT: Isaiah 9, Isaiah 10 | NT: 1 Timothy 3
    {272, 3, {{"OT", "Isaiah", 11}, {"OT", "Isaiah", 12}, {"OT", "Isaiah", 13}}}, // Day 272: OT: Isaiah 11, Isaiah 12, Isaiah 13 | NT: 
    {273, 3, {{"OT", "Isaiah", 14}, {"OT", "Isaiah", 15}, {"NT", "1 Timothy", 4}}}, // Day 273: OT: Isaiah 14, Isaiah 15 | NT: 1 Timothy 4
    {274, 4, {{"OT", "Isaiah", 16}, {"OT", "Isaiah", 17}, {"OT", "Isaiah", 18}, {"NT", "1 Timothy", 5}}}, // Day 274: OT: Isaiah 16, Isaiah 17, Isaiah 18 | NT: 1 Timothy 5
    {275, 2, {{"OT", "Isaiah", 19}, {"OT", "Isaiah", 20}}}, // Day 275: OT: Isaiah 19, Isaiah 20 | NT: 
    {276, 4, {{"OT", "Isaiah", 21}, {"OT", "Isaiah", 22}, {"OT", "Isaiah", 23}, {"NT", "1 Timothy", 6}}}, // Day 276: OT: Isaiah 21, Isaiah 22, Isaiah 23 | NT: 1 Timothy 6
    {277, 4, {{"OT", "Isaiah", 24}, {"OT", "Isaiah", 25}, {"OT", "Isaiah", 26}, {"NT", "2 Timothy", 1}}}, // Day 277: OT: Isaiah 24, Isaiah 25, Isaiah 26 | NT: 2 Timothy 1
    {278, 3, {{"OT", "Isaiah", 27}, {"OT", "Isaiah", 28}, {"NT", "2 Timothy", 2}}}, // Day 278: OT: Isaiah 27, Isaiah 28 | NT: 2 Timothy 2
    {279, 3, {{"OT", "Isaiah", 29}, {"OT", "Isaiah", 30}, {"OT", "Isaiah", 31}}}, // Day 279: OT: Isaiah 29, Isaiah 30, Isaiah 31 | NT: 
    {280, 3, {{"OT", "Isaiah", 32}, {"OT", "Isaiah", 33}, {"NT", "2 Timothy", 3}}}, // Day 280: OT: Isaiah 32, Isaiah 33 | NT: 2 Timothy 3
    {281, 4, {{"OT", "Isaiah", 34}, {"OT", "Isaiah", 35}, {"OT", "Isaiah", 36}, {"NT", "2 Timothy", 4}}}, // Day 281: OT: Isaiah 34, Isaiah 35, Isaiah 36 | NT: 2 Timothy 4
    {282, 2, {{"OT", "Isaiah", 37}, {"OT", "Isaiah", 38}}}, // Day 282: OT: Isaiah 37, Isaiah 38 | NT: 
    {283, 4, {{"OT", "Isaiah", 39}, {"OT", "Isaiah", 40}, {"OT", "Isaiah", 41}, {"NT", "Titus", 1}}}, // Day 283: OT: Isaiah 39, Isaiah 40, Isaiah 41 | NT: Titus 1
    {284, 3, {{"OT", "Isaiah", 42}, {"OT", "Isaiah", 43}, {"NT", "Titus", 2}}}, // Day 284: OT: Isaiah 42, Isaiah 43 | NT: Titus 2
    {285, 4, {{"OT", "Isaiah", 44}, {"OT", "Isaiah", 45}, {"OT", "Isaiah", 46}, {"NT", "Titus", 3}}}, // Day 285: OT: Isaiah 44, Isaiah 45, Isaiah 46 | NT: Titus 3
    {286, 2, {{"OT", "Isaiah", 47}, {"OT", "Isaiah", 48}}}, // Day 286: OT: Isaiah 47, Isaiah 48 | NT: 
    {287, 4, {{"OT", "Isaiah", 49}, {"OT", "Isaiah", 50}, {"OT", "Isaiah", 51}, {"NT", "Philemon", 1}}}, // Day 287: OT: Isaiah 49, Isaiah 50, Isaiah 51 | NT: Philemon 1
    {288, 4, {{"OT", "Isaiah", 52}, {"OT", "Isaiah", 53}, {"OT", "Isaiah", 54}, {"NT", "Hebrews", 1}}}, // Day 288: OT: Isaiah 52, Isaiah 53, Isaiah 54 | NT: Hebrews 1
    {289, 2, {{"OT", "Isaiah", 55}, {"OT", "Isaiah", 56}}}, // Day 289: OT: Isaiah 55, Isaiah 56 | NT: 
    {290, 4, {{"OT", "Isaiah", 57}, {"OT", "Isaiah", 58}, {"OT", "Isaiah", 59}, {"NT", "Hebrews", 2}}}, // Day 290: OT: Isaiah 57, Isaiah 58, Isaiah 59 | NT: Hebrews 2
    {291, 3, {{"OT", "Isaiah", 60}, {"OT", "Isaiah", 61}, {"NT", "Hebrews", 3}}}, // Day 291: OT: Isaiah 60, Isaiah 61 | NT: Hebrews 3
    {292, 4, {{"OT", "Isaiah", 62}, {"OT", "Isaiah", 63}, {"OT", "Isaiah", 64}, {"NT", "Hebrews", 4}}}, // Day 292: OT: Isaiah 62, Isaiah 63, Isaiah 64 | NT: Hebrews 4
    {293, 2, {{"OT", "Isaiah", 65}, {"OT", "Isaiah", 66}}}, // Day 293: OT: Isaiah 65, Isaiah 66 | NT: 
    {294, 4, {{"OT", "Jeremiah", 1}, {"OT", "Jeremiah", 2}, {"OT", "Jeremiah", 3}, {"NT", "Hebrews", 5}}}, // Day 294: OT: Jeremiah 1, Jeremiah 2, Jeremiah 3 | NT: Hebrews 5
    {295, 3, {{"OT", "Jeremiah", 4}, {"OT", "Jeremiah", 5}, {"NT", "Hebrews", 6}}}, // Day 295: OT: Jeremiah 4, Jeremiah 5 | NT: Hebrews 6
    {296, 3, {{"OT", "Jeremiah", 6}, {"OT", "Jeremiah", 7}, {"OT", "Jeremiah", 8}}}, // Day 296: OT: Jeremiah 6, Jeremiah 7, Jeremiah 8 | NT: 
    {297, 3, {{"OT", "Jeremiah", 9}, {"OT", "Jeremiah", 10}, {"NT", "Hebrews", 7}}}, // Day 297: OT: Jeremiah 9, Jeremiah 10 | NT: Hebrews 7
    {298, 4, {{"OT", "Jeremiah", 11}, {"OT", "Jeremiah", 12}, {"OT", "Jeremiah", 13}, {"NT", "Hebrews", 8}}}, // Day 298: OT: Jeremiah 11, Jeremiah 12, Jeremiah 13 | NT: Hebrews 8
    {299, 3, {{"OT", "Jeremiah", 14}, {"OT", "Jeremiah", 15}, {"OT", "Jeremiah", 16}}}, // Day 299: OT: Jeremiah 14, Jeremiah 15, Jeremiah 16 | NT: 
    {300, 3, {{"OT", "Jeremiah", 17}, {"OT", "Jeremiah", 18}, {"NT", "Hebrews", 9}}}, // Day 300: OT: Jeremiah 17, Jeremiah 18 | NT: Hebrews 9
    {301, 4, {{"OT", "Jeremiah", 19}, {"OT", "Jeremiah", 20}, {"OT", "Jeremiah", 21}, {"NT", "Hebrews", 10}}}, // Day 301: OT: Jeremiah 19, Jeremiah 20, Jeremiah 21 | NT: Hebrews 10
    {302, 3, {{"OT", "Jeremiah", 22}, {"OT", "Jeremiah", 23}, {"NT", "Hebrews", 11}}}, // Day 302: OT: Jeremiah 22, Jeremiah 23 | NT: Hebrews 11
    {303, 3, {{"OT", "Jeremiah", 24}, {"OT", "Jeremiah", 25}, {"OT", "Jeremiah", 26}}}, // Day 303: OT: Jeremiah 24, Jeremiah 25, Jeremiah 26 | NT: 
    {304, 3, {{"OT", "Jeremiah", 27}, {"OT", "Jeremiah", 28}, {"NT", "Hebrews", 12}}}, // Day 304: OT: Jeremiah 27, Jeremiah 28 | NT: Hebrews 12
    {305, 4, {{"OT", "Jeremiah", 29}, {"OT", "Jeremiah", 30}, {"OT", "Jeremiah", 31}, {"NT", "Hebrews", 13}}}, // Day 305: OT: Jeremiah 29, Jeremiah 30, Jeremiah 31 | NT: Hebrews 13
    {306, 2, {{"OT", "Jeremiah", 32}, {"OT", "Jeremiah", 33}}}, // Day 306: OT: Jeremiah 32, Jeremiah 33 | NT: 
    {307, 4, {{"OT", "Jeremiah", 34}, {"OT", "Jeremiah", 35}, {"OT", "Jeremiah", 36}, {"NT", "James", 1}}}, // Day 307: OT: Jeremiah 34, Jeremiah 35, Jeremiah 36 | NT: James 1
    {308, 3, {{"OT", "Jeremiah", 37}, {"OT", "Jeremiah", 38}, {"NT", "James", 2}}}, // Day 308: OT: Jeremiah 37, Jeremiah 38 | NT: James 2
    {309, 4, {{"OT", "Jeremiah", 39}, {"OT", "Jeremiah", 40}, {"OT", "Jeremiah", 41}, {"NT", "James", 3}}}, // Day 309: OT: Jeremiah 39, Jeremiah 40, Jeremiah 41 | NT: James 3
    {310, 3, {{"OT", "Jeremiah", 42}, {"OT", "Jeremiah", 43}, {"OT", "Jeremiah", 44}}}, // Day 310: OT: Jeremiah 42, Jeremiah 43, Jeremiah 44 | NT: 
    {311, 3, {{"OT", "Jeremiah", 45}, {"OT", "Jeremiah", 46}, {"NT", "James", 4}}}, // Day 311: OT: Jeremiah 45, Jeremiah 46 | NT: James 4
    {312, 4, {{"OT", "Jeremiah", 47}, {"OT", "Jeremiah", 48}, {"OT", "Jeremiah", 49}, {"NT", "James", 5}}}, // Day 312: OT: Jeremiah 47, Jeremiah 48, Jeremiah 49 | NT: James 5
    {313, 2, {{"OT", "Jeremiah", 50}, {"OT", "Jeremiah", 51}}}, // Day 313: OT: Jeremiah 50, Jeremiah 51 | NT: 
    {314, 4, {{"OT", "Jeremiah", 52}, {"OT", "Lamentations", 1}, {"OT", "Lamentations", 2}, {"NT", "1 Peter", 1}}}, // Day 314: OT: Jeremiah 52, Lamentations 1, Lamentations 2 | NT: 1 Peter 1
    {315, 3, {{"OT", "Lamentations", 3}, {"OT", "Lamentations", 4}, {"NT", "1 Peter", 2}}}, // Day 315: OT: Lamentations 3, Lamentations 4 | NT: 1 Peter 2
    {316, 4, {{"OT", "Lamentations", 5}, {"OT", "Ezekiel", 1}, {"OT", "Ezekiel", 2}, {"NT", "1 Peter", 3}}}, // Day 316: OT: Lamentations 5, Ezekiel 1, Ezekiel 2 | NT: 1 Peter 3
    {317, 2, {{"OT", "Ezekiel", 3}, {"OT", "Ezekiel", 4}}}, // Day 317: OT: Ezekiel 3, Ezekiel 4 | NT: 
    {318, 4, {{"OT", "Ezekiel", 5}, {"OT", "Ezekiel", 6}, {"OT", "Ezekiel", 7}, {"NT", "1 Peter", 4}}}, // Day 318: OT: Ezekiel 5, Ezekiel 6, Ezekiel 7 | NT: 1 Peter 4
    {319, 3, {{"OT", "Ezekiel", 8}, {"OT", "Ezekiel", 9}, {"NT", "1 Peter", 5}}}, // Day 319: OT: Ezekiel 8, Ezekiel 9 | NT: 1 Peter 5
    {320, 3, {{"OT", "Ezekiel", 10}, {"OT", "Ezekiel", 11}, {"OT", "Ezekiel", 12}}}, // Day 320: OT: Ezekiel 10, Ezekiel 11, Ezekiel 12 | NT: 
    {321, 4, {{"OT", "Ezekiel", 13}, {"OT", "Ezekiel", 14}, {"OT", "Ezekiel", 15}, {"NT", "2 Peter", 1}}}, // Day 321: OT: Ezekiel 13, Ezekiel 14, Ezekiel 15 | NT: 2 Peter 1
    {322, 3, {{"OT", "Ezekiel", 16}, {"OT", "Ezekiel", 17}, {"NT", "2 Peter", 2}}}, // Day 322: OT: Ezekiel 16, Ezekiel 17 | NT: 2 Peter 2
    {323, 4, {{"OT", "Ezekiel", 18}, {"OT", "Ezekiel", 19}, {"OT", "Ezekiel", 20}, {"NT", "2 Peter", 3}}}, // Day 323: OT: Ezekiel 18, Ezekiel 19, Ezekiel 20 | NT: 2 Peter 3
    {324, 2, {{"OT", "Ezekiel", 21}, {"OT", "Ezekiel", 22}}}, // Day 324: OT: Ezekiel 21, Ezekiel 22 | NT: 
    {325, 4, {{"OT", "Ezekiel", 23}, {"OT", "Ezekiel", 24}, {"OT", "Ezekiel", 25}, {"NT", "1 John", 1}}}, // Day 325: OT: Ezekiel 23, Ezekiel 24, Ezekiel 25 | NT: 1 John 1
    {326, 3, {{"OT", "Ezekiel", 26}, {"OT", "Ezekiel", 27}, {"NT", "1 John", 2}}}, // Day 326: OT: Ezekiel 26, Ezekiel 27 | NT: 1 John 2
    {327, 3, {{"OT", "Ezekiel", 28}, {"OT", "Ezekiel", 29}, {"OT", "Ezekiel", 30}}}, // Day 327: OT: Ezekiel 28, Ezekiel 29, Ezekiel 30 | NT: 
    {328, 3, {{"OT", "Ezekiel", 31}, {"OT", "Ezekiel", 32}, {"NT", "1 John", 3}}}, // Day 328: OT: Ezekiel 31, Ezekiel 32 | NT: 1 John 3
    {329, 4, {{"OT", "Ezekiel", 33}, {"OT", "Ezekiel", 34}, {"OT", "Ezekiel", 35}, {"NT", "1 John", 4}}}, // Day 329: OT: Ezekiel 33, Ezekiel 34, Ezekiel 35 | NT: 1 John 4
    {330, 3, {{"OT", "Ezekiel", 36}, {"OT", "Ezekiel", 37}, {"NT", "1 John", 5}}}, // Day 330: OT: Ezekiel 36, Ezekiel 37 | NT: 1 John 5
    {331, 3, {{"OT", "Ezekiel", 38}, {"OT", "Ezekiel", 39}, {"OT", "Ezekiel", 40}}}, // Day 331: OT: Ezekiel 38, Ezekiel 39, Ezekiel 40 | NT: 
    {332, 4, {{"OT", "Ezekiel", 41}, {"OT", "Ezekiel", 42}, {"OT", "Ezekiel", 43}, {"NT", "2 John", 1}}}, // Day 332: OT: Ezekiel 41, Ezekiel 42, Ezekiel 43 | NT: 2 John 1
    {333, 3, {{"OT", "Ezekiel", 44}, {"OT", "Ezekiel", 45}, {"NT", "3 John", 1}}}, // Day 333: OT: Ezekiel 44, Ezekiel 45 | NT: 3 John 1
    {334, 3, {{"OT", "Ezekiel", 46}, {"OT", "Ezekiel", 47}, {"OT", "Ezekiel", 48}}}, // Day 334: OT: Ezekiel 46, Ezekiel 47, Ezekiel 48 | NT: 
    {335, 3, {{"OT", "Daniel", 1}, {"OT", "Daniel", 2}, {"NT", "Jude", 1}}}, // Day 335: OT: Daniel 1, Daniel 2 | NT: Jude 1
    {336, 4, {{"OT", "Daniel", 3}, {"OT", "Daniel", 4}, {"OT", "Daniel", 5}, {"NT", "Revelation", 1}}}, // Day 336: OT: Daniel 3, Daniel 4, Daniel 5 | NT: Revelation 1
    {337, 3, {{"OT", "Daniel", 6}, {"OT", "Daniel", 7}, {"NT", "Revelation", 2}}}, // Day 337: OT: Daniel 6, Daniel 7 | NT: Revelation 2
    {338, 3, {{"OT", "Daniel", 8}, {"OT", "Daniel", 9}, {"OT", "Daniel", 10}}}, // Day 338: OT: Daniel 8, Daniel 9, Daniel 10 | NT: 
    {339, 3, {{"OT", "Daniel", 11}, {"OT", "Daniel", 12}, {"NT", "Revelation", 3}}}, // Day 339: OT: Daniel 11, Daniel 12 | NT: Revelation 3
    {340, 4, {{"OT", "Hosea", 1}, {"OT", "Hosea", 2}, {"OT", "Hosea", 3}, {"NT", "Revelation", 4}}}, // Day 340: OT: Hosea 1, Hosea 2, Hosea 3 | NT: Revelation 4
    {341, 2, {{"OT", "Hosea", 4}, {"OT", "Hosea", 5}}}, // Day 341: OT: Hosea 4, Hosea 5 | NT: 
    {342, 4, {{"OT", "Hosea", 6}, {"OT", "Hosea", 7}, {"OT", "Hosea", 8}, {"NT", "Revelation", 5}}}, // Day 342: OT: Hosea 6, Hosea 7, Hosea 8 | NT: Revelation 5
    {343, 4, {{"OT", "Hosea", 9}, {"OT", "Hosea", 10}, {"OT", "Hosea", 11}, {"NT", "Revelation", 6}}}, // Day 343: OT: Hosea 9, Hosea 10, Hosea 11 | NT: Revelation 6
    {344, 3, {{"OT", "Hosea", 12}, {"OT", "Hosea", 13}, {"NT", "Revelation", 7}}}, // Day 344: OT: Hosea 12, Hosea 13 | NT: Revelation 7
    {345, 3, {{"OT", "Hosea", 14}, {"OT", "Joel", 1}, {"OT", "Joel", 2}}}, // Day 345: OT: Hosea 14, Joel 1, Joel 2 | NT: 
    {346, 3, {{"OT", "Joel", 3}, {"OT", "Amos", 1}, {"NT", "Revelation", 8}}}, // Day 346: OT: Joel 3, Amos 1 | NT: Revelation 8
    {347, 4, {{"OT", "Amos", 2}, {"OT", "Amos", 3}, {"OT", "Amos", 4}, {"NT", "Revelation", 9}}}, // Day 347: OT: Amos 2, Amos 3, Amos 4 | NT: Revelation 9
    {348, 2, {{"OT", "Amos", 5}, {"OT", "Amos", 6}}}, // Day 348: OT: Amos 5, Amos 6 | NT: 
    {349, 4, {{"OT", "Amos", 7}, {"OT", "Amos", 8}, {"OT", "Amos", 9}, {"NT", "Revelation", 10}}}, // Day 349: OT: Amos 7, Amos 8, Amos 9 | NT: Revelation 10
    {350, 3, {{"OT", "Obadiah", 1}, {"OT", "Jonah", 1}, {"NT", "Revelation", 11}}}, // Day 350: OT: Obadiah 1, Jonah 1 | NT: Revelation 11
    {351, 4, {{"OT", "Jonah", 2}, {"OT", "Jonah", 3}, {"OT", "Jonah", 4}, {"NT", "Revelation", 12}}}, // Day 351: OT: Jonah 2, Jonah 3, Jonah 4 | NT: Revelation 12
    {352, 2, {{"OT", "Micah", 1}, {"OT", "Micah", 2}}}, // Day 352: OT: Micah 1, Micah 2 | NT: 
    {353, 4, {{"OT", "Micah", 3}, {"OT", "Micah", 4}, {"OT", "Micah", 5}, {"NT", "Revelation", 13}}}, // Day 353: OT: Micah 3, Micah 4, Micah 5 | NT: Revelation 13
    {354, 4, {{"OT", "Micah", 6}, {"OT", "Micah", 7}, {"OT", "Nahum", 1}, {"NT", "Revelation", 14}}}, // Day 354: OT: Micah 6, Micah 7, Nahum 1 | NT: Revelation 14
    {355, 2, {{"OT", "Nahum", 2}, {"OT", "Nahum", 3}}}, // Day 355: OT: Nahum 2, Nahum 3 | NT: 
    {356, 4, {{"OT", "Habakkuk", 1}, {"OT", "Habakkuk", 2}, {"OT", "Habakkuk", 3}, {"NT", "Revelation", 15}}}, // Day 356: OT: Habakkuk 1, Habakkuk 2, Habakkuk 3 | NT: Revelation 15
    {357, 3, {{"OT", "Zephaniah", 1}, {"OT", "Zephaniah", 2}, {"NT", "Revelation", 16}}}, // Day 357: OT: Zephaniah 1, Zephaniah 2 | NT: Revelation 16
    {358, 4, {{"OT", "Zephaniah", 3}, {"OT", "Haggai", 1}, {"OT", "Haggai", 2}, {"NT", "Revelation", 17}}}, // Day 358: OT: Zephaniah 3, Haggai 1, Haggai 2 | NT: Revelation 17
    {359, 2, {{"OT", "Zechariah", 1}, {"OT", "Zechariah", 2}}}, // Day 359: OT: Zechariah 1, Zechariah 2 | NT: 
    {360, 4, {{"OT", "Zechariah", 3}, {"OT", "Zechariah", 4}, {"OT", "Zechariah", 5}, {"NT", "Revelation", 18}}}, // Day 360: OT: Zechariah 3, Zechariah 4, Zechariah 5 | NT: Revelation 18
    {361, 3, {{"OT", "Zechariah", 6}, {"OT", "Zechariah", 7}, {"NT", "Revelation", 19}}}, // Day 361: OT: Zechariah 6, Zechariah 7 | NT: Revelation 19
    {362, 3, {{"OT", "Zechariah", 8}, {"OT", "Zechariah", 9}, {"OT", "Zechariah", 10}}}, // Day 362: OT: Zechariah 8, Zechariah 9, Zechariah 10 | NT: 
    {363, 3, {{"OT", "Zechariah", 11}, {"OT", "Zechariah", 12}, {"NT", "Revelation", 20}}}, // Day 363: OT: Zechariah 11, Zechariah 12 | NT: Revelation 20
    {364, 4, {{"OT", "Zechariah", 13}, {"OT", "Zechariah", 14}, {"OT", "Malachi", 1}, {"NT", "Revelation", 21}}}, // Day 364: OT: Zechariah 13, Zechariah 14, Malachi 1 | NT: Revelation 21
    {365, 4, {{"OT", "Malachi", 2}, {"OT", "Malachi", 3}, {"OT", "Malachi", 4}, {"NT", "Revelation", 22}}}, // Day 365: OT: Malachi 2, Malachi 3, Malachi 4 | NT: Revelation 22
};
