#!/usr/bin/env python3
"""
Generate precalculated Bible reading plan for 2026
Two parallel plans: Old Testament and New Testament
"""

# Old Testament (39 books) - 929 total chapters
ot_books = [
    ("Genesis", 50), ("Exodus", 40), ("Leviticus", 27), ("Numbers", 36), ("Deuteronomy", 34),
    ("Joshua", 24), ("Judges", 21), ("Ruth", 4), ("1 Samuel", 31), ("2 Samuel", 24),
    ("1 Kings", 22), ("2 Kings", 25), ("1 Chronicles", 29), ("2 Chronicles", 36), ("Ezra", 10),
    ("Nehemiah", 13), ("Esther", 10), ("Job", 42), ("Psalm", 150), ("Proverbs", 31),
    ("Ecclesiastes", 12), ("Song of Solomon", 8), ("Isaiah", 66), ("Jeremiah", 52), ("Lamentations", 5),
    ("Ezekiel", 48), ("Daniel", 12), ("Hosea", 14), ("Joel", 3), ("Amos", 9),
    ("Obadiah", 1), ("Jonah", 4), ("Micah", 7), ("Nahum", 3), ("Habakkuk", 3),
    ("Zephaniah", 3), ("Haggai", 2), ("Zechariah", 14), ("Malachi", 4)
]

# New Testament (27 books) - 260 total chapters
nt_books = [
    ("Matthew", 28), ("Mark", 16), ("Luke", 24), ("John", 21), ("Acts", 28),
    ("Romans", 16), ("1 Corinthians", 16), ("2 Corinthians", 13), ("Galatians", 6), ("Ephesians", 6),
    ("Philippians", 4), ("Colossians", 4), ("1 Thessalonians", 5), ("2 Thessalonians", 3), ("1 Timothy", 6),
    ("2 Timothy", 4), ("Titus", 3), ("Philemon", 1), ("Hebrews", 13), ("James", 5),
    ("1 Peter", 5), ("2 Peter", 3), ("1 John", 5), ("2 John", 1), ("3 John", 1),
    ("Jude", 1), ("Revelation", 22)
]

def chapter_index_to_book_chapter(chapter_idx, book_list):
    """Convert 0-based chapter index to (book_name, chapter_number)"""
    cumulative = 0
    for book_name, chapter_count in book_list:
        if chapter_idx < cumulative + chapter_count:
            chapter_num = (chapter_idx - cumulative) + 1
            return book_name, chapter_num
        cumulative += chapter_count
    return None, None

def generate_reading_plan():
    """Generate complete 365-day reading plan with parallel OT and NT"""
    ot_total_chapters = sum(count for _, count in ot_books)  # 929
    nt_total_chapters = sum(count for _, count in nt_books)  # 260
    total_days = 365

    plan = []

    for day in range(1, 366):  # Days 1-365
        # OT reading
        ot_start_idx = ((day - 1) * ot_total_chapters) // total_days
        ot_end_idx = (day * ot_total_chapters) // total_days - 1

        ot_readings = []
        for idx in range(ot_start_idx, ot_end_idx + 1):
            book, chapter = chapter_index_to_book_chapter(idx, ot_books)
            if book:
                ot_readings.append(('OT', book, chapter))

        # NT reading
        nt_start_idx = ((day - 1) * nt_total_chapters) // total_days
        nt_end_idx = (day * nt_total_chapters) // total_days - 1

        nt_readings = []
        for idx in range(nt_start_idx, nt_end_idx + 1):
            book, chapter = chapter_index_to_book_chapter(idx, nt_books)
            if book:
                nt_readings.append(('NT', book, chapter))

        # Combine OT and NT readings
        day_readings = ot_readings + nt_readings
        plan.append(day_readings)

    return plan

def format_c_string(s):
    """Escape a string for C code"""
    return s.replace('"', '\\"')

def generate_c_code(plan):
    """Generate C code for the precalculated plan"""

    print("// Precalculated Bible reading plan for 2026 (365 days)")
    print("// Auto-generated by generate_2026_plan.py")
    print("// Parallel OT and NT reading plans")
    print("// OT: 929 chapters, NT: 260 chapters")
    print("")
    print("typedef struct {")
    print("    const char *testament;  // \"OT\" or \"NT\"")
    print("    const char *book;")
    print("    int chapter;")
    print("} DailyReading;")
    print("")
    print("typedef struct {")
    print("    int day_of_year;  // 1-365")
    print("    int count;        // Number of chapters total (OT + NT)")
    print("    DailyReading readings[10];  // Max 10 chapters per day")
    print("} DayPlan;")
    print("")
    print("static const DayPlan daily_plan_2026[365] = {")

    for day_num, day_readings in enumerate(plan, 1):
        readings_str = ", ".join(
            f'{{"{testament}", "{format_c_string(book)}", {chapter}}}'
            for testament, book, chapter in day_readings
        )

        # Format comment with OT and NT separated
        ot_list = [f"{book} {chapter}" for testament, book, chapter in day_readings if testament == 'OT']
        nt_list = [f"{book} {chapter}" for testament, book, chapter in day_readings if testament == 'NT']
        comment = f" // Day {day_num}: OT: " + ", ".join(ot_list) + " | NT: " + ", ".join(nt_list)

        print(f"    {{{day_num}, {len(day_readings)}, {{{readings_str}}}}},{comment}")

    print("};")

def main():
    plan = generate_reading_plan()

    # Print summary
    ot_count = sum(1 for day in plan for t, _, _ in day if t == 'OT')
    nt_count = sum(1 for day in plan for t, _, _ in day if t == 'NT')

    print("// Summary of 2026 Bible Reading Plan", file=__import__('sys').stderr)
    print(f"// Total days: {len(plan)}", file=__import__('sys').stderr)
    print(f"// OT chapters: {ot_count}", file=__import__('sys').stderr)
    print(f"// NT chapters: {nt_count}", file=__import__('sys').stderr)
    print(f"// Total chapters: {sum(len(day) for day in plan)}", file=__import__('sys').stderr)
    print(f"// Min chapters/day: {min(len(day) for day in plan)}", file=__import__('sys').stderr)
    print(f"// Max chapters/day: {max(len(day) for day in plan)}", file=__import__('sys').stderr)
    print(f"// Avg chapters/day: {sum(len(day) for day in plan) / len(plan):.2f}", file=__import__('sys').stderr)
    print("", file=__import__('sys').stderr)

    generate_c_code(plan)

if __name__ == "__main__":
    main()
