# GitHub Actions CI configuration for Craft
# Copy this to .github/workflows/ci-checks.yml to enable CI

name: Code Quality Checks

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang-tidy

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --inconclusive --std=c99 \
          --suppress=missingIncludeSystem \
          --suppress=unusedFunction \
          -I Craft/src -I Craft/deps \
          Craft/src/*.c \
          2> cppcheck-report.txt
        cat cppcheck-report.txt

    - name: Upload cppcheck report
      uses: actions/upload-artifact@v3
      with:
        name: cppcheck-report
        path: cppcheck-report.txt

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libglfw3-dev \
          libglew-dev libcurl4-openssl-dev libsqlite3-dev

    - name: Build
      run: |
        cd Craft
        cmake .
        make

    - name: Build with AddressSanitizer
      run: |
        cd Craft
        mkdir -p build_asan
        cd build_asan
        cmake -DCMAKE_C_FLAGS="-fsanitize=address -fno-omit-frame-pointer -g" \
              -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" ..
        make

  valgrind-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind build-essential cmake \
          libglfw3-dev libglew-dev libcurl4-openssl-dev libsqlite3-dev

    - name: Build
      run: |
        cd Craft
        cmake -DCMAKE_BUILD_TYPE=Debug .
        make

    # Note: Running valgrind on GUI apps in CI is tricky
    # This is a placeholder for when we add unit tests
    - name: Run valgrind (placeholder)
      run: |
        echo "Valgrind check would run here with unit tests"
